### ISSUE TITLE
create voting stats logic

### ISSUE THREAD

**Issue by atwfk** [m3ntorship/pickify-frontend#110]
- [x] create a helper function that calculates the option group votes and returns total votes
- [x] create a helper function that calculates votes and total votes and returns the result progress
- [x] create a helper function that returns max and min option votes to identify most, least and runner option
- [x] add tests to the functions

**Comment by Nilegfx** [comment]
> create a helper function that returns max and min option votes to identify winner, loser and runner option

there is no loser.

**Comment by atwfk** [comment]
we have it here in molecules, should we remove it and have only runners and winner ?

![Screenshot from 2021-05-23 13-01-11](https://user-images.githubusercontent.com/52901348/119257768-08798600-bbc7-11eb-8fdf-4183e74e3731.png)

**Comment by Nilegfx** [comment]
ok. I need to discuss this with Mostafa. for now, at least let's not call it loser. `most` and `least` votes should do the job
