### ISSUE TITLE
createPoll component.

### ISSUE THREAD

**Issue by AhmedAdel999** [m3ntorship/pickify-frontend#141]
This is the parent component for(createImagePoll, createTextPoll and createMiniSurvey)
- It should be the same as the [design](https://www.figma.com/file/y1c0A9oQFKX4SwKB9jGwdD/Pickify-(mostafa)?node-id=1196%3A62).
- It should have enough test cases to cover the main functionality of the component
- It should have the right type.
- Make sure to check [the coding standards](https://docs.google.com/document/d/1G53Pq8LbWUmwfINdqNgEoaoQi3DpCIabusB212y0wSQ/edit#
).

**Comment by ahmedelsayad11** [comment]
this issue is solved in the post creation component
