### ISSUE TITLE
imagePollView component

### ISSUE THREAD

**Issue by AhmedAdel999** [m3ntorship/pickify-frontend#155]
- It should be identical to the [design](https://www.figma.com/file/y1c0A9oQFKX4SwKB9jGwdD/Pickify-(mostafa)?node-id=1196%3A62)
![image](https://user-images.githubusercontent.com/67234505/120718554-bdfee000-c4c9-11eb-8651-58aa21a5b8c9.png)
![image](https://user-images.githubusercontent.com/67234505/120718566-c2c39400-c4c9-11eb-9786-3b224eefe017.png)
![image](https://user-images.githubusercontent.com/67234505/120718576-c6571b00-c4c9-11eb-8c6e-089601cb758c.png)
- It should be responsive.
- It should have unit tests.

**Comment by atwfk** [comment]
we need to decide what library that will be used for this slider 
![Screenshot from 2021-06-04 18-29-35](https://user-images.githubusercontent.com/52901348/120834108-e38bf800-c562-11eb-93f2-f4f6ddbbb64c.png)
