### ISSUE TITLE
**Use tailwindcss classes in with CSS module**

### ISSUE THREAD

**Issue by elhaw** [m3ntorship/pickify-frontend#17]
### Issue descripotion

- tailwindcss classes are not generated even the configuration is added and all packages  are installed
- using the @apply inside the [Name.module.css] shows an error in dev tools  says that the key is invalid `it considers it a key `
### Expected Result

- Since Tailwind is a PostCSS plugin so CSS module files should be processed with it and work fine
- tailwind classes should be generated

### Root Casue
- The [name.modules.css] are not processed with `postcss` .

### Solution 
- reaname  the below files from `tailwind.config.ts` . `postcss.config.ts `to `.js`   `tailwind.config.js`, `postcss.config.js`

## note
- As Nextjs project is bundled by `Webpack`  ( may be `postcss.config.ts` files does not work ) as I am not aware of the whole flow so we can  go for the solution above and later we can invsitage.

**Comment by AhmedAdel999** [comment]
Tailwind classes doesn't work

**How to reproduce the problem:**
Try adding any tailwind class in a component(for example the articles component)
**What happens**
The styles associated with that class doesn't apply
**Expected behaviour**
The styles get applied
