### ISSUE TITLE
Prop `id` did not match. Server: "id_5724023739" Client: "id_1174932510"

### ISSUE THREAD

**Issue by Ali-Khamis** [m3ntorship/pickify-frontend#180]
![Screenshot from 2021-06-10 22-24-44](https://user-images.githubusercontent.com/68826445/121592254-bc3d9b00-ca3a-11eb-90d6-414d7f59c9b5.png)
- [Link](https://youtu.be/dt5HEHJoMQU) to a video describing the issue and how we fixed it

-Fixed the error with canceling the component rendering with SSR
This Code from [Next docs](https://nextjs.org/docs/advanced-features/dynamic-import)  was helpfull :

```typescript 
import dynamic from 'next/dynamic'
const DynamicComponentWithNoSSR = dynamic(
  () => import('../components/hello3'),
  { ssr: false }
)

function Home() {
  return (
    <div>
      <Header />
      <DynamicComponentWithNoSSR />
      <p>HOME PAGE is here!</p>
    </div>
  )
}
export default Home 
```

*note: we still do NOT know the reason of the error

**Comment by ahmedkhitaby** [comment]
we have added ```useEffect()``` hook to prevent this part of the component from rendering at the server-side and only rendering it at the client-side
