### ISSUE TITLE
Prevent usage of button elements without an explicit type attribute (react/button-has-type)

### ISSUE THREAD

**Issue by ahmedelsayad11** [m3ntorship/pickify-frontend#181]
The default value of type attribute for button HTML element is "submit" which is often not the desired behavior and may lead to unexpected page reloads. This rules enforces an explicit type attribute for all the button elements and checks that its value is valid per spec (i.e., is one of "button", "submit", and "reset").

I could not make the type of the button accept a variable or prop so that anyone can reuse it and pass the type as he desires 
but eslint complained that type should be statically typed  and not be passed

**Comment by elhaw** [comment]
We found this [issue](https://github.com/yannickcr/eslint-plugin-react/issues/1555 ) related to that error  
the solution is to disable this rule using `/* eslint-disable react/button-has-type */`

If you have some time to check it @Nilegfx  ❤️

**Comment by Nilegfx** [comment]
an example, PLEASE.

**Comment by elhaw** [comment]
@Nilegfx  will add a code example 👍

**Comment by Nilegfx** [comment]
no need. I read the example from the mentioned issue.

Please go ahead with disabling the role
