### ISSUE TITLE
making component's names descriptive

### ISSUE THREAD

**Issue by omarawad0** [m3ntorship/pickify-frontend#208]
There are some component's names not being named descriptively. this should be solved. for example:

- **Misc** molecule should be changed to a more descriptive name like ErrorMessage.
- **TextDefault** molecule should be changed to a more descriptive name like TextOptionInput.
and so on.

There are components not following a consistent naming style: 

- **CreateImagePoll** should be renamed to the following style like the rest organisms >> **TextPollCreation** and **MiniSurveyPollCreation**.
 and so on.

**Comment by atwfk** [comment]
i will rename **ImageUpload** component to **UploadButton** as it may receive in the future other file types not only images
but i will link the pr to [this issue](https://github.com/m3ntorship/pickify-frontend/issues/209) so it will contain all the component changes

**Comment by omarawad0** [comment]
are there any component names that need to be renamed besides the **misc** component?
