### ISSUE TITLE
snapshot testing doesn't work

### ISSUE THREAD

**Issue by AhmedAdel999** [m3ntorship/pickify-frontend#24]
Snapshot testing isn't working as react-test-renderer isn't installed.

**Comment by AhmedAdel999** [comment]
Instead of opening another issue I will describe the problem here since it's also related to snapshot testing
when running these tests
![image](https://user-images.githubusercontent.com/67234505/117553237-99d9eb80-b050-11eb-9635-10b3610be0ad.png)
I get the following errors
![image](https://user-images.githubusercontent.com/67234505/117553252-b4ac6000-b050-11eb-803f-66c33b9ccd71.png)

**Comment by elhaw** [comment]
@AhmedAdel999 
If you could not push that PR due to these errors. try to add in steps how to reproduce this error.

**Comment by AhmedAdel999** [comment]
**How to reproduce this error:**

1. Add a test file that performs a naive snapshot testing (you can try that against the Heading component) as such
![image](https://user-images.githubusercontent.com/67234505/117553461-17522b80-b052-11eb-9227-29cd131f2342.png)
2. Run `yarn run test`
