### ISSUE TITLE
Post : share button functionality 

### ISSUE THREAD

**Issue by elhaw** [m3ntorship/pickify-frontend#332]
### Description 

- The `share` button at post footer does not have any functionality. 
<img width="761" alt="Screen Shot 2021-07-28 at 10 13 27 PM" src="https://user-images.githubusercontent.com/8650435/127389694-4f1cf98d-c85b-4d80-8f62-3382ea4d8866.png">

### Requirement 
- once a user clicks on this icon the `post` should be sharable : `construct the post URL so that it can be shared`

**Comment by Nilegfx** [comment]
we can automatically copy the url for viewing a single post and show notification that the link is in the user clipboard
