### ISSUE TITLE
handle uuid on user state changes

### ISSUE THREAD

**Issue by atwfk** [m3ntorship/pickify-frontend#418]
- Currently we are only saving the uuid of the user only when logging in, when firebase token expires it creates a new token calling `onAuthStateChanged` and since we are not saving the uuid in this function the delete button is never shown, as a suggestion we can call `register` function which sets uuid in `authStateChanged`.
- Also it turns out we have another issue before even talking the the back end via `register` function, the user is actually logged in and redirected to the home page.

**Comment by elhaw** [comment]
@atwfk, please do not forget to describe the bug and how to reproduce it 👍
