### ISSUE TITLE
**Creating Image Vote Results**

### ISSUE THREAD

**Issue by Ali-Khamis** [m3ntorship/pickify-frontend#89]
Please check the [design](https://www.figma.com/file/y1c0A9oQFKX4SwKB9jGwdD/Pickify-mostafa?node-id=1196%3A64) for **Image Vote & like cases** in the page named **Post View**
![Screenshot from 2021-06-07 13-12-49](https://user-images.githubusercontent.com/68826445/121007296-27b10f80-c792-11eb-92c8-98dd8c610cac.png)

notices that :
1. You will have to wait until someone finishes the [Image Caption Component](https://github.com/m3ntorship/pickify-frontend/issues/87) so you can use it)
2. you have to use the voting stats molecule

**Acceptance criteria**
- [ ] IMPORTANT to be responsive
- [ ] typescript  declaration
- [ ] reusable
- [ ] mimic the design
- [ ] cover all variants
- [ ] storybook
- [ ] test the component

**Comment by ahmedelsayad11** [comment]
this issue is already solved in the image poll option component
