### ISSUE TITLE
A form label must be associated with a control

### ISSUE THREAD

**Issue by ahmedelsayad11** [m3ntorship/pickify-frontend#98]
when using an HTML input tag with a label,
I tried to put the label first then the input tag or vice versa 
![Capture](https://user-images.githubusercontent.com/68955535/118751909-6e31df00-b862-11eb-8824-bf37a1731f15.PNG)

but it shows an error 
![Capture](https://user-images.githubusercontent.com/68955535/118751976-8f92cb00-b862-11eb-95fb-2f23265e486e.PNG)

even though I put an htmlFor attribute but still give me the same error
![Capture](https://user-images.githubusercontent.com/68955535/118752550-940bb380-b863-11eb-83c7-b79fc8db653f.PNG)

the solution that I found was to make the input inside the label
![Capture](https://user-images.githubusercontent.com/68955535/118752170-e4cedc80-b862-11eb-92b1-2383350183ea.PNG)

**Comment by ahmedkhitaby** [comment]
I solved it by adding the below lines in the ``.eslintrc`` file:
```javascript
{
    ....
    "rules": {
      "jsx-a11y/label-has-associated-control": ["error", {
        "required": {
          "some": ["nesting", "id"]
        }
      }],
    },
    ...
}
```
